import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
              <body className="min-h-full flex flex-col">
          <nav className="flex flex-wrap gap-4 p-4 text-sm sm:text-base justify-end">
<a href="/">Home</a>
<a href="/upload">Upload</a>
<a href="/review">Review</a>
<a href="/export">Export</a>
<a href="/health-check">Health Check</a>
</nav>
{children}
        </body>
    </html>
  );
}
